sudo: false
language: node_js
cache:
  directories:
    - node_modules
    - bower_components
after_script:
  - npm run coveralls
before_deploy:
  - ./travis/build.sh
deploy:
  - provider: s3
    access_key_id: AKIAJHBUIN7T5C5BML2Q
    secret_access_key:
      secure: VMiWVya4zfyabg9dCr6eYwKx1RDKBdE0KN9CJnYJtLO0k8elM+yWwu7Nq1TyrXtJz/oFVcIMCqkw/+cRr38HYrVLsYUOYDYhJM9FsJQi4vITR/pBWfgL21cK6rTQU7LXF6XmhokazT9xp22Sb1q6SSWtfR1PyNlsjDg918ePNTE=
    bucket: dev-dd-ehealth-org-ng
    region: eu-west-1
    local-dir: dist
    skip_cleanup: true
    on:
      repo: eHealthAfrica/direct-delivery-dashboard
      branch: develop
  - provider: s3
    access_key_id: AKIAJHBUIN7T5C5BML2Q
    secret_access_key:
      secure: VMiWVya4zfyabg9dCr6eYwKx1RDKBdE0KN9CJnYJtLO0k8elM+yWwu7Nq1TyrXtJz/oFVcIMCqkw/+cRr38HYrVLsYUOYDYhJM9FsJQi4vITR/pBWfgL21cK6rTQU7LXF6XmhokazT9xp22Sb1q6SSWtfR1PyNlsjDg918ePNTE=
    bucket: travis-direct-delivery-dashboard-staging
    region: eu-west-1
    local-dir: dist
    skip_cleanup: true
    on:
      repo: eHealthAfrica/direct-delivery-dashboard
      branch: master
  - provider: s3
    access_key_id: AKIAJHBUIN7T5C5BML2Q
    secret_access_key:
      secure: VMiWVya4zfyabg9dCr6eYwKx1RDKBdE0KN9CJnYJtLO0k8elM+yWwu7Nq1TyrXtJz/oFVcIMCqkw/+cRr38HYrVLsYUOYDYhJM9FsJQi4vITR/pBWfgL21cK6rTQU7LXF6XmhokazT9xp22Sb1q6SSWtfR1PyNlsjDg918ePNTE=
    bucket: travis-direct-delivery-dashboard-production
    region: eu-west-1
    local-dir: dist
    skip_cleanup: true
    on:
      repo: eHealthAfrica/direct-delivery-dashboard
      tags: true
